lint:
  stage: test
  image: cr.gfx.cafe/build/img/nodejs:latest
  cache:
    paths:
      - node_modules/
    key:
      files:
        - package-lock.json
  script:
    - npm i
    - npm run lint

test:
  stage: test
  image: cr.gfx.cafe/build/img/nodejs:latest
  cache:
    paths:
      - node_modules/
    key:
      files:
        - package-lock.json
  script:
    - npm i
    - npx hardhat clean
    - npx hardhat test
